Repository blackMisay/vet-management, pull requests merged in 2024-11, with the labels that each got.

#79 bug/VCMS74
  app/Core/Repository/ServiceRepository.cs
  app/View/Services/frmServices.cs
  app/view/Client/frmClientModal.Designer.cs
Labels: bug, review

#80 feature/VCMS70 - Account Management Module
  app/Core/Model/User.cs
  app/Core/Repository/UserAuthentication.cs
  app/Core/Repository/UserRepository.cs
  app/Properties/Resources.Designer.cs
  app/Properties/Resources.resx
  app/Resources/Sahagun_logo_1.jpg
  app/Resources/Sahagun_logo_2.jpg
  app/Resources/user.png
  app/View/Administration/frmAdmin.Designer.cs
  app/View/Administration/frmAdmin.cs
  app/View/Administration/frmAdmin.resx
  app/View/Administration/frmAdminModal.Designer.cs
  app/View/Administration/frmAdminModal.cs
  app/View/Administration/frmLogin.Designer.cs
  app/View/Administration/frmLogin.cs
  app/app.csproj
  app/view/frmMain.Designer.cs
  app/view/frmMain.cs
  app/view/frmMain.resx
Labels: November 2024, new feature, review

#81 defect/VCMS65 - [Code refactor] Remove unnecessary duplicate views in the project
  app/Core/Model/Barangay.cs
  app/Core/Model/Brand.cs
  app/Core/Model/Breed.cs
  app/Core/Model/City.cs
  app/Core/Model/Client.cs
  app/Core/Model/ColourPattern.cs
  app/Core/Model/Gender.cs
  app/Core/Model/Inventory.cs
  app/Core/Model/Pet.cs
  app/Core/Model/Product.cs
  app/Core/Model/ProductCategory.cs
  app/Core/Model/Province.cs
  app/Core/Model/Region.cs
  app/Core/Model/Services.cs
  app/Core/Model/Species.cs
  app/Core/Repository/PetRepository.cs
  app/Core/Repository/ProductRepository.cs
  app/Core/Repository/ServiceRepository.cs
  app/Program.cs
  app/View/Administration/frmAdmin.cs
  app/View/Administration/frmAdminModal.cs
  app/View/Administration/frmLogin.cs
  app/View/Client/frmClient.cs
  app/View/Client/frmClientPatientModal.cs
  app/View/Maintenance/frmMaintenanceModal.Designer.cs
  app/View/Maintenance/frmMaintenanceModal.cs
  app/View/Patient/AddClient.Designer.cs
  app/View/Patient/AddClient.cs
  app/View/Patient/AddClient.resx
  app/View/Patient/AddPet.Designer.cs
  app/View/Patient/AddPet.cs
  app/View/Patient/AddPet.resx
  app/View/Patient/PatientList.Designer.cs
  app/View/Patient/PatientList.cs
  app/View/Patient/PatientList.resx
  app/View/Patient/PetDetails.Designer.cs
  app/View/Patient/PetDetails.cs
  app/View/Patient/PetDetails.resx
  app/View/Product/frmProductModal.cs
  app/View/Services/frmServices.cs
  app/View/Services/frmServicesModal.cs
  app/View/Transaction/frmTransaction.Designer.cs
  app/View/Transaction/frmTransaction.cs
  app/app.csproj
  app/view/Client/frmClient.cs
  app/view/Client/frmClientModal.cs
  app/view/Client/frmClientPatientModal.cs
  app/view/Patient/AddClient.Designer.cs
  app/view/frmMain.Designer.cs
Labels: November 2024, revision, review

#77 bug/VCMS75
  app/Core/Repository/ServiceRepository.cs
  app/Core/Repository/UpgradeFile.cs
  app/View/Services/frmServices.Designer.cs
  app/View/Services/frmServices.cs
  app/View/Services/frmServicesModal.Designer.cs
  app/View/Services/frmServicesModal.cs
Labels: bug, review

#82 enhance/VCMS68
  app/Core/Model/Product.cs
  app/Core/Model/Types.cs
  app/Core/Repository/MaintenanceRepository.cs
  app/Core/Repository/ProductRepository.cs
  app/View/Maintenance/frmMaintenanceModal.Designer.cs
  app/View/Maintenance/frmMaintenanceModal.cs
  app/View/Maintenance/frmMaintenanceModal.resx
  app/View/Product/frmProductModal.Designer.cs
  app/View/Product/frmProductModal.cs
  app/View/Product/frmProducts.Designer.cs
  app/View/Product/frmProducts.resx
  app/app.csproj
Labels: enhancement

#86 feature/VCMS69
  app/Properties/Resources.Designer.cs
  app/Properties/Resources.resx
  app/Resources/project-management.png
  app/View/Inventory/frmInventory.Designer.cs
  app/View/Inventory/frmInventory.cs
  app/View/Inventory/frmInventory.resx
  app/View/Inventory/frmInventoryModal.cs
  app/View/Product/frmProducts.Designer.cs
  app/View/Product/frmProducts.resx
  app/app.csproj
  app/icons/logo1-removebg-preview (2).ico
Labels: November 2024, new feature

#90 feature/VCMS69
  app/View/Inventory/frmInventory.Designer.cs
  app/View/Inventory/frmInventory.resx
  app/app.csproj
  app/view/Inventory/frmInventory.Designer.cs
  app/view/Inventory/frmInventory.resx
Labels: new feature

#93 feature/VCMS69
  app/Core/Model/Inventory.cs
  app/Core/Repository/InventoryRepository.cs
  app/View/Inventory/frmInventory.Designer.cs
  app/View/Inventory/frmInventory.cs
  app/View/Inventory/frmInventory.resx
  app/View/Inventory/frmInventoryModal.cs
  app/view/Inventory/frmInventory.Designer.cs
  app/view/Inventory/frmInventory.resx
Labels: new feature

#95 enhance/VCMS85
  app/Core/Model/Product.cs
  app/Core/Repository/ProductRepository.cs
  app/View/Product/frmProductModal.Designer.cs
  app/View/Product/frmProductModal.cs
  app/View/Product/frmProducts.Designer.cs
  app/View/Product/frmProducts.resx
Labels: enhancement

#94 feature/VCMS69
  app/Core/Model/Inventory.cs
  app/Core/Repository/InventoryRepository.cs
  app/Core/Repository/ProductRepository.cs
  app/Properties/Resources.Designer.cs
  app/Properties/Resources.resx
  app/Resources/logo1-removebg-preview (3).ico
  app/Resources/sahagun.png
  app/View/Inventory/frmInventory.Designer.cs
  app/View/Inventory/frmInventory.cs
  app/View/Inventory/frmInventory.resx
  app/View/Inventory/frmInventoryModal.Designer.cs
  app/View/Inventory/frmInventoryModal.cs
  app/View/Product/frmProductModal.Designer.cs
  app/View/Product/frmProductModal.cs
  app/View/Product/frmProducts.Designer.cs
  app/View/Product/frmProducts.cs
  app/View/Product/frmProducts.resx
  app/app.csproj
  app/view/Inventory/frmInventory.Designer.cs
  app/view/Inventory/frmInventory.resx
Labels: new feature

#97 feature/VCMS69
  app/View/Inventory/frmInventory.Designer.cs
  app/View/Inventory/frmInventory.cs
  app/View/Product/frmProducts.cs
  app/view/Inventory/frmInventory.Designer.cs
Labels: enhancement

#98 feature/VCMS69
  app/View/Inventory/frmInventory.cs
Labels: enhancement
