Repository blackMisay/vet-management, pull requests merged in 2024-05, with the labels that each got.

#28 feature/VCMS24
  app/View/Product/frmProducts.Designer.cs
  app/View/Product/frmProducts.cs
  app/View/Product/frmProducts.resx
  app/app.csproj
  app/view/Client/frmClient.Designer.cs
  app/view/Client/frmClient.resx
Labels: enhancement

#31 Feature/VCMS30
  app/Core/Model/Services.cs
  app/Core/Repository/ServiceRepository.cs
  app/View/Client/frmClient.cs
  app/View/Services/frmServices.Designer.cs
  app/View/Services/frmServices.cs
  app/View/Services/frmServices.resx
  app/View/Services/frmServicesModal.Designer.cs
  app/View/Services/frmServicesModal.cs
  app/View/Services/frmServicesModal.resx
  app/app.csproj
  app/view/Client/frmClient.cs
  app/view/frmMain.Designer.cs
  app/view/frmMain.cs
Labels: new feature

#29 feature/VCMS23
  app/View/Inventory/frmInventory.Designer.cs
  app/View/Inventory/frmInventory.cs
  app/View/Inventory/frmInventory.resx
  app/app.csproj
Labels: enhancement

#38 feature/VCMS36
  app/Properties/Resources.Designer.cs
  app/Properties/Resources.resx
  app/Resources/icons8-data-backup-16.png
  app/Resources/icons8-data-backup-32.png
  app/Resources/icons8-restore-16.png
  app/Resources/icons8-restore-32.png
  app/View/Maintenance/frmMaintenanceModal.Designer.cs
  app/View/Maintenance/frmMaintenanceModal.cs
  app/View/Maintenance/frmMaintenanceModal.resx
  app/app.csproj
Labels: new feature

#43 feature/VCMS39
  app/Core/Model/Client.cs
  app/Core/Model/ColourPattern.cs
  app/Core/Model/Pet.cs
  app/Core/Repository/ClientRepository.cs
  app/Core/Repository/PetRepository.cs
  app/View/Client/frmClient.cs
  app/View/Client/frmClientPatientModal.cs
  app/View/Patient/AddPet.cs
  app/app.csproj
  app/view/Client/frmClient.Designer.cs
  app/view/Client/frmClient.cs
  app/view/Client/frmClient.resx
  app/view/Client/frmClientModal.Designer.cs
  app/view/Client/frmClientModal.cs
  app/view/Client/frmClientPatientModal.cs
Labels: bug

#44 feature/VCMS42
  app/Core/Repository/ServiceRepository.cs
  app/View/Services/frmServices.Designer.cs
  app/View/Services/frmServices.cs
  app/View/Services/frmServices.resx
  app/View/Services/frmServicesModal.Designer.cs
  app/View/Services/frmServicesModal.cs
Labels: bug
